//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBrain.Etls.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheBrain.Etls.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding content to excel file....
        /// </summary>
        internal static string AddContentToExcel {
            get {
                return ResourceManager.GetString("AddContentToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        internal static string CommandExamples {
            get {
                return ResourceManager.GetString("CommandExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional params:.
        /// </summary>
        internal static string CommandOptionalParams {
            get {
                return ResourceManager.GetString("CommandOptionalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}={2} (Run the specified command).
        /// </summary>
        internal static string CommandParamUsage {
            get {
                return ResourceManager.GetString("CommandParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.exe {1}={2} {3}=C:\temp\test.xlsx {4}=C:\Users\user\Brains\U01\B04.
        /// </summary>
        internal static string CommandSample1 {
            get {
                return ResourceManager.GetString("CommandSample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.exe {1}={2} {3}=C:\temp\test.xlsx {4}=C:\Users\user\Brains\U01\B04 {5}=en.
        /// </summary>
        internal static string CommandSample2 {
            get {
                return ResourceManager.GetString("CommandSample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string CommandUsage {
            get {
                return ResourceManager.GetString("CommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;TheBrain content file name&gt; (Default = {2}).
        /// </summary>
        internal static string ContentFileParamUsage {
            get {
                return ResourceManager.GetString("ContentFileParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create еxcel file from &apos;TheBrain&apos; application data.
        /// </summary>
        internal static string CreateExcelFile {
            get {
                return ResourceManager.GetString("CreateExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;TheBrain database file name&gt; (Default = {2}).
        /// </summary>
        internal static string DatabaseFileParamUsage {
            get {
                return ResourceManager.GetString("DatabaseFileParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;TheBrain database folder path.
        /// </summary>
        internal static string DatabaseParamUsage {
            get {
                return ResourceManager.GetString("DatabaseParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file &apos;{0}&apos; not found.
        /// </summary>
        internal static string DbFileNotFound {
            get {
                return ResourceManager.GetString("DbFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file &apos;{0}&apos; is empty.
        /// </summary>
        internal static string ExcelFileEmpty {
            get {
                return ResourceManager.GetString("ExcelFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file name is empty.
        /// </summary>
        internal static string ExcelFileNameEmpty {
            get {
                return ResourceManager.GetString("ExcelFileNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file &apos;{0}&apos; not found.
        /// </summary>
        internal static string ExcelFileNotFound {
            get {
                return ResourceManager.GetString("ExcelFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file path &apos;{0}&apos; not found.
        /// </summary>
        internal static string ExcelFilePathNotFound {
            get {
                return ResourceManager.GetString("ExcelFilePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;Excel file path&gt;.
        /// </summary>
        internal static string ExcelParamUsage {
            get {
                return ResourceManager.GetString("ExcelParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; in use by another process.
        /// </summary>
        internal static string FileLocked {
            get {
                return ResourceManager.GetString("FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files count: {0}.
        /// </summary>
        internal static string FilesCount {
            get {
                return ResourceManager.GetString("FilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content &apos;{0}&apos; files not found.
        /// </summary>
        internal static string FilesNotFound {
            get {
                return ResourceManager.GetString("FilesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &apos;{0}&apos; files in &apos;{1}&apos; folder.
        /// </summary>
        internal static string FindFiles {
            get {
                return ResourceManager.GetString("FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;Set application lang ru/en&gt; (Default = {2}).
        /// </summary>
        internal static string LangParamUsage {
            get {
                return ResourceManager.GetString("LangParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data from &apos;{0}&apos;.
        /// </summary>
        internal static string LoadDataFromDb {
            get {
                return ResourceManager.GetString("LoadDataFromDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;Log file path&gt; (Default = {2}).
        /// </summary>
        internal static string LogFileParamUsage {
            get {
                return ResourceManager.GetString("LogFileParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;TheBrain old format content file name&gt; (Default = {2}).
        /// </summary>
        internal static string OldFormatContentFileNameParamUsage {
            get {
                return ResourceManager.GetString("OldFormatContentFileNameParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}=&lt;TheBrain old format content folder name&gt; (Default = {2}).
        /// </summary>
        internal static string OldFormatContentFolderNameParamUsage {
            get {
                return ResourceManager.GetString("OldFormatContentFolderNameParamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; not specified.
        /// </summary>
        internal static string ParameterNotSpecified {
            get {
                return ResourceManager.GetString("ParameterNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; not found.
        /// </summary>
        internal static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed: {0} of {1}.
        /// </summary>
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the &quot;Restore Brain Index&quot; command after updating the content.
        /// </summary>
        internal static string RebuildBrainIndexWarning {
            get {
                return ResourceManager.GetString("RebuildBrainIndexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: file &apos;{1}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string RowFileNotFound {
            get {
                return ResourceManager.GetString("RowFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: row doesn&apos;t contain content Id.
        /// </summary>
        internal static string RowWithoutId {
            get {
                return ResourceManager.GetString("RowWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row {0}: content id &apos;{1}&apos; doesn&apos;t exist in db.
        /// </summary>
        internal static string RowWrongId {
            get {
                return ResourceManager.GetString("RowWrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command: {0}.
        /// </summary>
        internal static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving excel file to &apos;{0}&apos;....
        /// </summary>
        internal static string SavingExcelFile {
            get {
                return ResourceManager.GetString("SavingExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See log file: &apos;{0}&apos;.
        /// </summary>
        internal static string SeeLogFilePath {
            get {
                return ResourceManager.GetString("SeeLogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoughts count: {0}.
        /// </summary>
        internal static string ThoughtsCount {
            get {
                return ResourceManager.GetString("ThoughtsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload content  from еxcel file to &apos;TheBrain&apos; application .
        /// </summary>
        internal static string UploadFilesFromExcelFile {
            get {
                return ResourceManager.GetString("UploadFilesFromExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command completed successfully.
        /// </summary>
        internal static string СommandCompleted {
            get {
                return ResourceManager.GetString("СommandCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сommand completed with error(s).
        /// </summary>
        internal static string СommandCompletedError {
            get {
                return ResourceManager.GetString("СommandCompletedError", resourceCulture);
            }
        }
    }
}
